# Generated by Django 5.0.1 on 2024-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('property_type', models.CharField(max_length=50)),
                ('property_status', models.CharField(choices=[('on_sale', 'On Sale'), ('on_rent', 'On Rent')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('garages', models.IntegerField()),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
                ('map_link', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='property_img')),
            ],
        ),
    ]
