# Generated by Django 5.0.1 on 2024-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('townhose', 'Townhouse'), ('shop', 'Shop'), ('garage', 'Garage')], max_length=50),
        ),
    ]
