# Generated by Django 5.0.1 on 2024-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaan', '0002_alter_properties_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_status',
            field=models.CharField(choices=[('featured', 'Featured'), ('on_sale', 'On Sale'), ('on_rent', 'On Rent')], max_length=50),
        ),
    ]
